FROM python:3.9.5-slim-buster

# set work directory
WORKDIR /usr/src

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# copy project
COPY ./app ./app