version: '3.8'

services:
  app:
    build: .
    environment:
      TELEGRAM_BOT_ID: ${TELEGRAM_BOT_ID}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    ports:
      - 8000:8000
    depends_on:
      - ngrok

  ngrok:
    image: wernight/ngrok:armhf
    ports:
      - 4040:4040
    environment:
      NGROK_PROTOCOL: http
      NGROK_PORT: app:80
      NGROK_AUTH: ${NGROK_AUTH}
